services:
  # Service Frontend (React)
  - type: web
    name: ocr-correction-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /
    
  # Service Backend (Express + Python)
  - type: web
    name: opencorrection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: HEALTH_CHECK_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GOOGLE_VISION_CREDENTIALS
        sync: false
    healthCheckPath: /healthz
    healthCheckTimeout: 5
    autoDeploy: true 